use_frameworks!
inhibit_all_warnings!

def shared_pods

end

def rxswift_pods
    pod 'RxSwift', '~> 3.0'
    pod 'RxCocoa', '~> 3.0'
    pod 'RxDataSources'
    pod 'RxViewController'
end

def tool_pods
    pod 'CryptoSwift'
    pod 'SnapKit', '~> 3.2.0'
end

def ui_build_pods
    pod 'SwipeableTabBarController'
    pod 'FoldingTabBar', '~> 1.1'
    pod 'lottie-ios'
end

target 'Careless' do
    shared_pods
    rxswift_pods
    tool_pods
    ui_build_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
